### PR TITLE
[#645] Fix colors for radio and checkbox components in high contrast light mode

### LINKED ISSUE #645: Update High Contrast setup for Checkbox and Radio button
based on updates from the accessibility team, the high contrast mode should be updated as follows:
* if disabled: nothing specific to do
* if enabled: important semantic components/elements (like checkbox or radio buttons) must use the "color.content.default" color token to be displayed in light & dark mode

Note that this "color.content.default" color can also be the color used for the hover state.
Note also that it is recommended to be able to distinguish the enabled and the hover states.
Therefore when the high contrast mode is activated, the hover state must display the focus border.

### PR DESCRIPTION
**Pull request by pylapp**
### Related issues

Closes #645 

### Description

For radio button and checkbox components, if high contrast mode is enabled and device in light mode, change some colors for better contrast ratio without impacting hover, pressed, or error states.

### Motivation & Context

But compliant with a11y rules

### Types of change

- Bug fix (non-breaking which fixes an issue)

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

- [x] My change follows accessibility good practices

#### Design

- [x] My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [x] I checked my changes do not add new SwiftLint warnings
- [x]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [x] The evolution have been tested and the project builds for iPhones and iPads
- [x] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
- (NA) Design review has been done
- (NA)  Accessibility review has been done
- (NA) Q/A team has tested the evolution
- [x] Documentation has been updated if relevant
- [x] Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [x] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues
- [ ]  [The wiki](https://github.com/Orange-OpenSource/ouds-ios/wiki) has been updated if needed _(optional)_

### CODE REVIEW

File: OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemBordersModifier.swift [hunk 1]
```diff
@@ -69,7 +72,11 @@ struct ControlItemBordersModifier: ViewModifier {
         if layoutData.isError {
             isOn ? theme.colors.colorActionNegativeEnabled : nil
         } else {
-            isOn ? theme.colors.colorActionSelected : nil
+            if colorSchemeContrast == .increased, colorScheme == .light {
+                theme.colors.colorContentDefault
```
Comment (ludovic35) [inline OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemBordersModifier.swift:76]: je pense que ça devrait être :
isOn ? theme.colors.colorContentDefault : nil

File: OUDS/Core/Components/Sources/Radio/Internal/RadioIndicatorModifiers.swift [hunk 2]
```diff
@@ -77,7 +80,11 @@ private struct RadioIndicatorForegroundModifier: ViewModifier {
         if isError {
             theme.colors.colorActionNegativeEnabled
         } else {
-            isOn ? theme.colors.colorActionSelected : theme.colors.colorActionEnabled
+            if colorSchemeContrast == .increased, colorScheme == .light {
+                theme.colors.colorContentDefault
```
Comment (ludovic35) [inline OUDS/Core/Components/Sources/Radio/Internal/RadioIndicatorModifiers.swift:84]: idem

File: OUDS/Core/Components/Sources/Radio/Internal/RadioIndicatorModifiers.swift [hunk 3]
```diff
@@ -191,7 +200,11 @@ private struct RadioIndicatorBorderModifier: ViewModifier {
...
```
Comment (ludovic35) [inline OUDS/Core/Components/Sources/Radio/Internal/RadioIndicatorModifiers.swift:204]: idem

File: OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemBordersModifier.swift (hunk 1 above)
Comment (pylapp) [reply OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemBordersModifier.swift:76]: Non. On ne change la couleur quand le cas précis du mode _high contrast_ en _light mode_, donc dans le cas contraire on garde le token actuel.
